version: '3.8'
services:
  client:
    image: react-app
    stdin_open: true
    build:
      dockerfile: Dockerfile
      context: './client'
    ports:
      - "3000:3000"
  api-server:
    build:
      dockerfile: Dockerfile
      context: './server'
    ports:
      - "5001:5001"
